inicialization project
baza-trainee/127-zbir pull request #5
Opened 2024-06-12 11:14 UTC by VitaliyPritula

верстка блока про дрони без поп апа

2024-06-12 11:14 UTC, VitaliyPritula commented
верстка блока про дрони без поп апа

2024-06-12 15:37 UTC, baza-trainee requested changes
і іконка-стрілочка в нас є в папці assets

2024-06-12 15:37 UTC, baza-trainee commented on src/components/Reason/Reason.jsx
> +            <h3 className={S.reason__title}>Розвідка і спостереження</h3>
ось ці тайтли в нас є на них клас - subtitle, зміни будь ласка по такому ж принципу  className="title"
І я би краще створила файл data.json і запхнула туди весь текст і мапила його, щоб не дублювати цю красоту

2024-06-13 18:16 UTC, baza-trainee approved these changes

2024-06-13 18:18 UTC, merged